[package]
name = "bevy_lyon_path_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_prototype_lyon = "0.5"
itertools = "0.10"
